const alluserTypes = {
    GET_ALLUSERS: 'GET_ALLUSERS',
    UPDATE_ALLUSER: 'UPDATE_ALLUSER',
    DELETE_ALLUSER: 'DELETE_ALLUSER',
    CREATE_ALLUSER: 'CREATE_ALLUSER',
}
export default alluserTypes