const classroomTypes = {
  GET_CLASSROOMS: "GET_CLASSROOMS",
  UPDATE_CLASSROOM: "UPDATE_CLASSROOM",
  DELETE_CLASSROOM: "DELETE_CLASSROOM",
  CREATE_CLASSROOM: "CREATE_CLASSROOM",
}
export default classroomTypes
