const examslotTypes = {
    GET_EXAMSLOTS: 'GET_EXAMSLOTS',
    UPDATE_EXAMSLOT: 'UPDATE_EXAMSLOT',
    DELETE_EXAMSLOT: 'DELETE_EXAMSLOT',
    CREATE_EXAMSLOT: 'CREATE_EXAMSLOT',


}
export default examslotTypes