const examscheduleTypes = {
  GET_EXAMSCHEDULES: "GET_EXAMSCHEDULES",
  CREATE_EXAMSCHEDULE: "CREATE_EXAMSCHEDULE",
  GENERATE_EXAMSCHEDULE: "GENERATE_EXAMSCHEDULE",
  GET_EXAMSCHEDULE_DETAILS: "GET_EXAMSCHEDULE_DETAILS",
}
export default examscheduleTypes
