const semesterTypes = {
    GET_SEMESTERS: 'GET_SEMESTERS',
    UPDATE_SEMESTER: 'UPDATE_SEMESTER',
    DELETE_SEMESTER: 'DELETE_SEMESTER',
    CREATE_SEMESTER: 'CREATE_SEMESTER',
}
export default semesterTypes