const studentTypes = {
  GET_STUDENTS: "GET_STUDENTS",
  UPDATE_STUDENT: "UPDATE_STUDENT",
  DELETE_STUDENT: "DELETE_STUDENT",
  CREATE_STUDENT: "CREATE_STUDENT",
  GET_ALL_STUDENTS: "GET_ALL_STUDENTS",
};
export default studentTypes;
